export const PERM_USUARIOS_VER = "USUARIOS_VER";
export const PERM_USUARIOS_CREAR = "USUARIOS_CREAR";
export const PERM_USUARIOS_EDITAR = "USUARIOS_EDITAR";
export const PERM_USUARIOS_ELIMINAR = "USUARIOS_ELIMINAR";

export const PERM_ROLES_VER = "ROLES_VER";
export const PERM_ROLES_CREAR = "ROLES_CREAR";
export const PERM_ROLES_EDITAR = "ROLES_EDITAR";
export const PERM_ROLES_ELIMINAR = "ROLES_ELIMINAR";

export const PERM_ZONAS_VER = "ZONAS_VER";
export const PERM_ZONAS_CREAR = "ZONAS_CREAR";
export const PERM_ZONAS_EDITAR = "ZONAS_EDITAR";
export const PERM_ZONAS_ELIMINAR = "ZONAS_ELIMINAR";

export const PERM_CAMARAS_VER = "CAMARAS_VER";
export const PERM_CAMARAS_CREAR = "CAMARAS_CREAR";
export const PERM_CAMARAS_EDITAR = "CAMARAS_EDITAR";
export const PERM_CAMARAS_ELIMINAR = "CAMARAS_ELIMINAR";

export const PERM_ALERTAS_VER = "ALERTAS_VER";
export const PERM_ALERTAS_CREAR = "ALERTAS_CREAR";
export const PERM_ALERTAS_EDITAR = "ALERTAS_EDITAR";
export const PERM_ALERTAS_ELIMINAR = "ALERTAS_ELIMINAR";
export const PERM_ALERTAS_JUSTIFICAR = "ALERTAS_JUSTIFICAR";

export const PERM_REPORTES_VER = "REPORTES_VER";
export const PERM_REPORTES_EXPORTAR = "REPORTES_EXPORTAR";

export const PERM_TIPOS_EPP_VER = "TIPOS_EPP_VER";

export const PERM_DASHBOARD_VER = "DASHBOARD_VER";

export const PERM_DETECCION_VER = "DETECCION_VER";

export const PERM_USAR_CAMARA_FALLBACK = "USAR_CAMARA_FALLBACK";

export const PERM_NIVELES_RIESGO_VER = "NIVELES_RIESGO_VER";
